<a href="https://colab.research.google.com/github/vishnuvardhan833199/DeepLearning/blob/main/IntroToDeepLearning1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#Step-1 installs:
!pip install numpy matplotlib scikit-learn


Theory:
A neuron computes:z=w1x1+w2x2+w3x3+.......+wnxn+b where x is inputs and w=weights and b=bias and z=output

In [ ]:
import numpy as np

In [ ]:
#Inputs:
X=np.array([2,3])
#weights:
W=np.array([0.5,0.8])
#Bias=1
b=1
#weighted sum
z=np.dot(X,W)+b #Here np.dot() becomes dot product
print("Output:",z)

Output: 4.4


In [ ]:
#Part-2 Multiple Neurons:
# 2inputs and 3 neurons:
#input:
X=np.array([2,3])
#weights for 3 neurons:
W=np.array([
    [0.5,0.8],
    [0.2,0.4],
    [0.9,0.1]
])
#biases:
b=np.array([1,1,1])
#Output:
z=np.dot(W,X)+b
print("Outputs:",z)

Outputs: [4.4 2.6 3.1]


In [ ]:
#Understanding the shapes:
X.shape #here(x,) means having x features

(2,)

In [ ]:
W.shape (x,y) means x neurons and each neuron has y weights

(3, 2)

In [ ]:
z.shape

(3,)

In [ ]:
#Part-3 Multiple Input samples(Batches)
#Real training never uses one sample:
#It uses batches:
#COde is:
#batch of inputs:
X=np.array([
    [2,3],
    [1,5],
    [4,2]
])
#weights:
W=np.array([
    [0.5,0.8],[0.2,0.4],[0.9,0.1]
])
#biases:
b=np.array([1,1,1])
#Forward pass:
z=np.dot(X,W.T)+b
print(z)

[[4.4 2.6 3.1]
 [5.5 3.2 2.4]
 [4.6 2.6 4.8]]


In [ ]:
X.shape #3 samples,2 features

(3, 2)

In [ ]:
W.shape #3 neurons having 2 weights each:

(3, 2)

In [ ]:
W.T.shape  #3samples,3 neuron weights;

(2, 3)

In [ ]:
print(W)

[[0.5 0.8]
 [0.2 0.4]
 [0.9 0.1]]


In [ ]:
print(W.T)

[[0.5 0.2 0.9]
 [0.8 0.4 0.1]]


PART-4 BUILDING A LAYER:

In [ ]:
class DenseLayer:
  def __init__(self,input_size,output_size):
    #Random weights:
    self.weights=np.random.randn(output_size,input_size)
    #biases: intilaised to zero:
    self.biases=np.zeros((1,output_size))
  def forward(self,X):
    #Store Input:
    self.input=X
    #Layer output:
    self.output=np.dot(X,self.weights.T)+self.biases
    return self.output

In [ ]:
np.random.randn(2,3)

array([[ 1.45064872,  0.27976335,  0.35474789],
       [-0.44197951, -1.06056496, -0.14835457]])

In [ ]:
#Test the layer
#inputs;

In [ ]:
X=np.array([
    [2,3],
    [1,5],
    [4,2]
])
#Create a layer:
layer=DenseLayer(input_size=2,output_size=3)
#Forward pass
output=layer.forward(X)
print(output)

[[ -0.50479994   2.23181926  -6.56017404]
 [ -0.55041264   3.78663963  -4.34780078]
 [ -0.66901398   1.41137566 -11.90010377]]


In [ ]:
#THe above output shows the 3 input samples and 3 neuron outputs